# Model parameters.
model:
  model: "GaiaAgent_VLMTool"
  2d_loss: 'focal'
  3d_loss: 'mse'
  exclude_zeros: False
  num_classes: 7
  loss_weights: [2, 1]
  2d_loss_weights: [0.3, 2.0, 2.0, 3.0, 1.5, 0.8, 1.0]
  focal_alpha: 0.5
  focal_gamma: 2
  class_ignored: 9999
  restore_checkpoints: '2d'

# Optimization parameters.
optim:
  num_epochs: 300
  lr: 0.0001
  optim_type: "adamw"
  momentum: 0.9
  nesterov: False
  beta: [0.9, 0.999]
  end_lr: 0.000005
  weight_decay: 0.001
  lr_schedule_type: "step_lr"
  step: 300
  gamma: 0.75
  last_epoch: 10

# Data parameters.
data:
  max_value: 151.401
  min_value: -73.0587
  augmentations: True
  mean: [0.5896145210542503, 0.6210658017517566, 0.591661801751776]
  std: [0.1898555514094201, 0.19114699478664082, 0.21242997453209553]
  train:
    path: './data/train/'
    text_path: './data/train/'
    batch_size: 2
  val:
    path: './data/val/'
  test:
    path: './data/test/'
